name: Build Test Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.1
          run_install: false
        # pnpm must be available before enabling pnpm caching in setup-node

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run extension tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pnpm --dir packages/extension test

      - name: Run relay tests
        run: pnpm --dir packages/relay test

      - name: Build relay package
        run: pnpm --dir packages/relay build

      - name: Compile extension
        run: pnpm --dir packages/extension compile

      - name: Package VSIX
        run: pnpm --dir packages/extension package-extension

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-as-mcp-server-vsix
          path: packages/extension/*.vsix

      - name: Determine extension version
        id: extension_version
        run: echo "version=$(node -p \"require('./packages/extension/package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extension_version.outputs.version }}
          name: VSCode as MCP Server v${{ steps.extension_version.outputs.version }}
          files: packages/extension/*.vsix
          draft: false
          prerelease: false
